'use strict';
/**
 * TOEIC 語彙デッキ（コロケーション中心）
 *
 *   id   : 一意ID
 *   term : 覚える塊。単語単体ではなく組み合わせを基本とする
 *   ja   : 短い訳。選択肢としてそのまま並ぶため、他の項目と重複しないこと
 *   ex   : term を含む例文
 *   note : 紛らわしい語との違いなど（任意）
 *
 * 出題は app.js の buildVocabQuestions() が英→日／日→英の両方向で生成する。
 */
const VOCAB_BANK = [
  { id: "w001", term: "place an order", ja: "注文する", ex: "Please place an order before the end of the month." },
  { id: "w002", term: "fill out a form", ja: "用紙に記入する", ex: "Fill out this form and return it to the front desk.", note: "fill in も可。fill out は書類全体を埋める意味。" },
  { id: "w003", term: "issue a refund", ja: "返金を出す", ex: "We will issue a refund within five business days." },
  { id: "w004", term: "submit an invoice", ja: "請求書を提出する", ex: "Please submit your invoice by the fifth of each month." },
  { id: "w005", term: "process a payment", ja: "支払いを処理する", ex: "The bank could not process the payment yesterday." },
  { id: "w006", term: "waive a fee", ja: "料金を免除する", ex: "The hotel agreed to waive the cancellation fee." },
  { id: "w007", term: "be eligible for", ja: "〜の資格がある", ex: "Part-time staff are eligible for a discount on meals.", note: "be eligible for=資格条件を満たす。be qualified for=技能・経験がある。" },
  { id: "w008", term: "meet a deadline", ja: "締切に間に合う", ex: "Our team met the deadline despite the staff shortage." },
  { id: "w009", term: "meet the requirements", ja: "要件を満たす", ex: "Your application does not meet the requirements for this position." },
  { id: "w010", term: "attend a conference", ja: "会議に出席する", ex: "She will attend a conference in Osaka next week.", note: "attend は他動詞で前置詞不要。attend to は「対処する」で別物。" },
  { id: "w011", term: "hold a meeting", ja: "会議を開く", ex: "We will hold a meeting to discuss the new policy." },
  { id: "w012", term: "reschedule for", ja: "日程を変更する", ex: "Can we reschedule the interview for Thursday morning?" },
  { id: "w013", term: "take minutes", ja: "議事録を取る", ex: "Ms. Tanaka will take minutes during the board meeting." },
  { id: "w014", term: "call off", ja: "中止する", ex: "The outdoor event was called off due to heavy rain.", note: "postpone は延期（後日やる）、call off は中止。" },
  { id: "w015", term: "fill a vacancy", ja: "欠員を補充する", ex: "We hope to fill the vacancy by the end of June." },
  { id: "w016", term: "conduct a survey", ja: "調査を実施する", ex: "The firm conducted a survey of local customers." },
  { id: "w017", term: "carry out an inspection", ja: "点検を実施する", ex: "Engineers will carry out an inspection of the boiler." },
  { id: "w018", term: "undergo renovation", ja: "改装中である", ex: "The lobby is undergoing renovation until early August." },
  { id: "w019", term: "be closed for repairs", ja: "修理のため閉鎖中", ex: "The east entrance is closed for repairs this week." },
  { id: "w020", term: "track a shipment", ja: "配送を追跡する", ex: "You can track your shipment using the number below." },
  { id: "w021", term: "ship an order", ja: "注文品を発送する", ex: "We shipped your order this morning by express delivery." },
  { id: "w022", term: "arrive on schedule", ja: "予定通りに着く", ex: "The container did not arrive on schedule last Friday.", note: "on schedule=予定通り。on time=時間ぴったり。" },
  { id: "w023", term: "be out of stock", ja: "在庫切れである", ex: "That model is out of stock until next month.", note: "discontinued は生産終了で再入荷なし。" },
  { id: "w024", term: "be delayed by", ja: "〜が原因で遅れる", ex: "The delivery was delayed by a customs inspection." },
  { id: "w025", term: "pick up an item", ja: "品物を受け取る", ex: "You may pick up your item at the service counter." },
  { id: "w026", term: "drop off a package", ja: "荷物を預ける", ex: "Please drop off the package at the security desk." },
  { id: "w027", term: "handle a complaint", ja: "苦情に対応する", ex: "Our staff handled the complaint quickly and politely." },
  { id: "w028", term: "address an issue", ja: "問題に取り組む", ex: "The manager promised to address the issue immediately.", note: "address は「対処する」。単に「話す」ではない。" },
  { id: "w029", term: "be in charge of", ja: "〜の責任者である", ex: "Ms. Lee is in charge of the marketing department.", note: "be in charge of=責任者。be responsible for=業務を負う。" },
  { id: "w030", term: "report to", ja: "〜の部下である", ex: "All interns report to the assistant manager.", note: "「報告する」だけでなく「〜の直属である」の意味が頻出。" },
  { id: "w031", term: "fill in for", ja: "代理を務める", ex: "Could you fill in for me at tomorrow's briefing?" },
  { id: "w032", term: "step down as", ja: "〜を辞任する", ex: "He will step down as chairman at the end of March." },
  { id: "w033", term: "be promoted to", ja: "〜に昇進する", ex: "She was promoted to regional director last year." },
  { id: "w034", term: "apply for a position", ja: "職に応募する", ex: "Over sixty people applied for the accounting position.", note: "apply for=応募する。apply to=（会社に）出願する・当てはまる。" },
  { id: "w035", term: "renew a contract", ja: "契約を更新する", ex: "We decided to renew the contract for another year." },
  { id: "w036", term: "sign an agreement", ja: "契約に署名する", ex: "Both companies signed the agreement on Monday afternoon." },
  { id: "w037", term: "terminate a contract", ja: "契約を解除する", ex: "Either party may terminate the contract with written notice.", note: "expire は自動詞で「期限が切れる」。" },
  { id: "w038", term: "be valid through", ja: "〜まで有効である", ex: "This coupon is valid through the end of September." },
  { id: "w039", term: "make a reservation", ja: "予約する", ex: "I made a reservation for a room with two beds." },
  { id: "w040", term: "board a flight", ja: "搭乗する", ex: "Passengers will board the flight from gate twelve." },
  { id: "w041", term: "be accompanied by", ja: "〜を添える必要がある", ex: "Returns must be accompanied by the original receipt." },
  { id: "w042", term: "outstanding balance", ja: "未払い残高", ex: "Please settle the outstanding balance by the end of this month.", note: "outstanding には「未払いの」と「傑出した」の両義がある。" },
  { id: "w043", term: "itemized invoice", ja: "明細付き請求書", ex: "The supplier sent an itemized invoice for last month's orders." },
  { id: "w044", term: "payment terms", ja: "支払い条件", ex: "Our standard payment terms are thirty days from the invoice date." },
  { id: "w045", term: "late fee", ja: "延滞料金", ex: "A late fee applies to invoices not paid within the period." },
  { id: "w046", term: "purchase order", ja: "発注書", ex: "Please attach the purchase order number to your invoice." },
  { id: "w047", term: "bulk discount", ja: "大口割引", ex: "We offer a bulk discount on orders over five hundred units." },
  { id: "w048", term: "reimbursement request", ja: "払い戻しの申請", ex: "Submit your reimbursement request within two weeks of travel.", note: "reimburse は立替分の精算。compensate は損害の補償。" },
  { id: "w049", term: "quarterly earnings", ja: "四半期の利益", ex: "The company reported strong quarterly earnings on Tuesday." },
  { id: "w050", term: "shipping charges", ja: "送料", ex: "Shipping charges are waived for orders placed online." },
  { id: "w051", term: "tracking number", ja: "追跡番号", ex: "You will receive a tracking number once your parcel ships." },
  { id: "w052", term: "damaged goods", ja: "破損した商品", ex: "Report any damaged goods to the carrier immediately." },
  { id: "w053", term: "inventory shortage", ja: "在庫不足", ex: "An inventory shortage delayed several customer orders." },
  { id: "w054", term: "distribution center", ja: "物流拠点", ex: "The new distribution center opens next to the highway." },
  { id: "w055", term: "expedited delivery", ja: "速達扱いの配送", ex: "Expedited delivery costs an additional fifteen dollars per package." },
  { id: "w056", term: "job opening", ja: "求人の空き枠", ex: "There is a job opening in the marketing department." },
  { id: "w057", term: "qualified applicant", ja: "適格な応募者", ex: "Only qualified applicants will be contacted for an interview." },
  { id: "w058", term: "cover letter", ja: "添え状", ex: "Attach a cover letter along with your updated resume." },
  { id: "w059", term: "probationary period", ja: "試用期間", ex: "New hires complete a three-month probationary period." },
  { id: "w060", term: "annual review", ja: "年次の人事評価", ex: "Your annual review is scheduled for the first week of December." },
  { id: "w061", term: "employee benefits", ja: "福利厚生", ex: "Employee benefits include health insurance and paid leave." },
  { id: "w062", term: "mandatory training", ja: "必須の研修", ex: "All staff must attend the mandatory training on safety.", note: "mandatory = required = compulsory。反対は optional / voluntary。" },
  { id: "w063", term: "routine maintenance", ja: "定期点検", ex: "The elevator is closed for routine maintenance this morning.", note: "repair は故障後の修理。maintenance は予防的。" },
  { id: "w064", term: "temporary closure", ja: "一時的な閉鎖", ex: "The parking lot faces a temporary closure during construction." },
  { id: "w065", term: "faulty equipment", ja: "故障した機器", ex: "Faulty equipment in the lab was replaced last week." },
  { id: "w066", term: "renovation project", ja: "改装工事", ex: "The lobby renovation project will finish by early spring." },
  { id: "w067", term: "building permit", ja: "建築許可証", ex: "The contractor is still waiting for the building permit.", note: "permit は可算の許可証。permission は不可算の許可。" },
  { id: "w068", term: "utility bill", ja: "光熱費の請求書", ex: "Our monthly utility bill rose sharply during the summer." },
  { id: "w069", term: "business trip", ja: "出張", ex: "She is on a business trip to Singapore until Friday." },
  { id: "w070", term: "boarding pass", ja: "搭乗券", ex: "Print your boarding pass before arriving at the airport." },
  { id: "w071", term: "connecting flight", ja: "乗り継ぎ便", ex: "My connecting flight to Chicago leaves in two hours." },
  { id: "w072", term: "complimentary breakfast", ja: "無料の朝食", ex: "The hotel offers complimentary breakfast to all guests.", note: "complimentary=無料。complementary=補完的。" },
  { id: "w073", term: "room rate", ja: "宿泊料金", ex: "The room rate includes internet access and parking." },
  { id: "w074", term: "itinerary change", ja: "旅程の変更", ex: "Please notify the agent of any itinerary change." },
  { id: "w075", term: "travel allowance", ja: "出張手当", ex: "Employees receive a daily travel allowance for meals." },
  { id: "w076", term: "tentative schedule", ja: "暫定の予定表", ex: "A tentative schedule for the conference was circulated yesterday." },
  { id: "w077", term: "agenda item", ja: "議題の項目", ex: "Budget cuts are the first agenda item this afternoon." },
  { id: "w078", term: "keynote speaker", ja: "基調講演者", ex: "The keynote speaker will address the audience at nine." },
  { id: "w079", term: "meeting minutes", ja: "議事録", ex: "Please email the meeting minutes to all participants." },
  { id: "w080", term: "prior approval", ja: "事前の承認", ex: "Overtime requires prior approval from your department head.", note: "prior notice は「事前の通知」。approval は「許可」。" },
  { id: "w081", term: "extended warranty", ja: "延長保証", ex: "Customers may purchase an extended warranty for two years." },
  { id: "w082", term: "defective item", ja: "不良品", ex: "Return any defective item within thirty days of purchase." },
  { id: "w083", term: "full refund", ja: "全額返金", ex: "We issued a full refund to the dissatisfied customer.", note: "replacement は代替品との交換。" },
  { id: "w084", term: "proof of purchase", ja: "購入の証明", ex: "Bring your receipt as proof of purchase for the exchange." },
  { id: "w085", term: "at your earliest convenience", ja: "ご都合のつき次第", ex: "Please return the signed contract at your earliest convenience.", note: "丁寧な催促。命令調を避けたいメールで使う。" },
  { id: "w086", term: "in the event of", ja: "〜の場合には", ex: "In the event of a delay, we will notify all passengers immediately.", note: "後ろは名詞。節が続くなら in the event that。" },
  { id: "w087", term: "no later than", ja: "遅くとも〜までに", ex: "Submit the expense report no later than Friday." },
  { id: "w088", term: "on behalf of", ja: "〜を代表して", ex: "I am writing on behalf of the marketing department." },
  { id: "w089", term: "in accordance with", ja: "〜に従って", ex: "All work must be done in accordance with safety regulations.", note: "規則・契約・方針に合わせる場合の定型。" },
  { id: "w090", term: "as of", ja: "〜の時点で", ex: "As of April 1, the new pricing takes effect.", note: "日付とセットで基準時点を示す。" },
  { id: "w091", term: "pending approval", ja: "承認待ちで", ex: "The budget increase is pending approval from headquarters." },
  { id: "w092", term: "effective immediately", ja: "即日発効で", ex: "Effective immediately, all visitors must sign in at reception.", note: "通達文の冒頭に置かれることが多い。" },
  { id: "w093", term: "in a timely manner", ja: "適時に", ex: "Please respond to customer inquiries in a timely manner." },
  { id: "w094", term: "subject to change", ja: "変更の可能性がある", ex: "Prices are subject to change without prior notice.", note: "be subject to は「〜の対象となる・〜を受ける」。" },
  { id: "w095", term: "with regard to", ja: "〜に関して", ex: "With regard to your invoice, we have processed the payment.", note: "regard は単数形。regards は誤り。" },
  { id: "w096", term: "prior to", ja: "〜より前に", ex: "Please review the agenda prior to the meeting.", note: "before の硬い言い方。後ろは名詞か動名詞。" },
  { id: "w097", term: "upon receipt of", ja: "受領し次第", ex: "We will ship the goods upon receipt of your payment.", note: "upon は「〜するとすぐに」。" },
  { id: "w098", term: "in lieu of", ja: "〜の代わりに", ex: "He took extra days off in lieu of overtime pay." },
  { id: "w099", term: "at no additional cost", ja: "追加料金なしで", ex: "Members receive express delivery at no additional cost." },
  { id: "w100", term: "in the meantime", ja: "その間に", ex: "In the meantime, please use the temporary parking lot." },
  { id: "w101", term: "as soon as possible", ja: "できるだけ早く", ex: "Please confirm your attendance as soon as possible." },
  { id: "w102", term: "in advance", ja: "前もって", ex: "Payment must be made two weeks in advance." },
  { id: "w103", term: "due to unforeseen circumstances", ja: "不測の事態により", ex: "The seminar was postponed due to unforeseen circumstances.", note: "中止・延期の告知で頻出。" },
  { id: "w104", term: "free of charge", ja: "無料で", ex: "Installation is provided free of charge to new subscribers." },
  { id: "w105", term: "on short notice", ja: "急な連絡で", ex: "Thank you for covering the shift on short notice." },
  { id: "w106", term: "until further notice", ja: "追って通知があるまで", ex: "The east entrance will remain closed until further notice." },
  { id: "w107", term: "ensure", ja: "確実にする", ex: "Please ensure that all doors are locked before leaving.", note: "insure=保険をかける、assure=人を安心させる。ensure の目的語は事柄。" },
  { id: "w108", term: "affect", ja: "〜に影響する（動詞）", ex: "The strike may affect delivery schedules next week.", note: "effect は名詞「影響・効果」。動詞なら affect。" },
  { id: "w109", term: "adopt", ja: "採用する", ex: "The board decided to adopt the new accounting system.", note: "adapt は「適応させる・改変する」。adopt はそのまま取り入れる。" },
  { id: "w110", term: "principal", ja: "主要な", ex: "Our principal concern is meeting the delivery deadline.", note: "principle は名詞「原則」のみ。形容詞で使えるのは principal。" },
  { id: "w111", term: "complement", ja: "補完する", ex: "The new software complements our existing inventory system.", note: "compliment は「褒め言葉・褒める」。complete と同語源なのが complement。" },
  { id: "w112", term: "personnel", ja: "人員・人事部", ex: "All personnel must attend the safety briefing on Monday.", note: "personal は「個人的な」。personnel は名詞で強勢は後ろ。" },
  { id: "w113", term: "economical", ja: "割安な", ex: "This hybrid model is more economical than the previous version.", note: "economic は「経済の（分野）」。節約になる意味は economical。" },
  { id: "w114", term: "respective", ja: "それぞれの", ex: "The managers returned to their respective offices after lunch.", note: "respectful は「敬意を払う」。" },
  { id: "w115", term: "considerate", ja: "思いやりのある", ex: "It was considerate of you to send a reminder email.", note: "considerable は「かなりの・相当な」。人柄なら considerate。" },
  { id: "w116", term: "industrious", ja: "勤勉な", ex: "The manager praised the industrious new intern.", note: "industrial は「産業の」。人を褒めるなら industrious。" },
  { id: "w117", term: "sensible", ja: "分別のある", ex: "Buying in bulk was a sensible decision for the office.", note: "sensitive は「敏感な・繊細な」。判断が賢明なら sensible。" },
  { id: "w118", term: "successive", ja: "連続した", ex: "Sales rose for the fifth successive quarter.", note: "successful は「成功した」。回数が続くのは successive。" },
  { id: "w119", term: "confidential", ja: "機密の", ex: "All client records are strictly confidential.", note: "confident は「自信がある」。書類・情報なら confidential。" },
  { id: "w120", term: "imply", ja: "ほのめかす", ex: "His email implied that the deadline might be extended.", note: "infer は聞き手が「推測する」。発信側が imply、受信側が infer。" },
  { id: "w121", term: "raise", ja: "〜を上げる（他動詞）", ex: "The company plans to raise wages next quarter.", note: "rise は自動詞で目的語を取らない。raise は必ず目的語が必要。" },
  { id: "w122", term: "lay", ja: "〜を置く（他動詞）", ex: "Please lay the documents on the conference table.", note: "lie は自動詞「横たわる」。目的語を取るのは lay。" },
];
